# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.

backend: Clipboard

matches:
  - trigger: "er;"
    replace: "espanso restart\n"

  # yabai restart
  - trigger: "yr;"
    replace: "brew services stop yabai && brew services start yabai\n"

  # Dates
  - trigger: ":datetest"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Grimoire Post Template
  - trigger: "post;"
    replace: "{{output}}"
    vars:
      - name: output
        type: script 
        params:
          args:
            - bash
            - "%CONFIG%/scripts/post.espanso"
          trim: false

  # Shell command example
  - trigger: ":xxxpost"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "bash %CONFIG%/scripts/post.espanso"

